inscripcion:
    pattern:  /
    defaults: { _controller: "UTNEventosBundle:Inscripcion:index" }

inscripcion_show:
    pattern:  /{id}/show
    defaults: { _controller: "UTNEventosBundle:Inscripcion:show" }

inscripcion_new:
    pattern:  /new
    defaults: { _controller: "UTNEventosBundle:Inscripcion:new" }

inscripcion_create:
    pattern:  /create
    defaults: { _controller: "UTNEventosBundle:Inscripcion:create" }
    requirements: { _method: post }

inscripcion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UTNEventosBundle:Inscripcion:edit" }

inscripcion_update:
    pattern:  /{id}/update
    defaults: { _controller: "UTNEventosBundle:Inscripcion:update" }
    requirements: { _method: post|put }

inscripcion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UTNEventosBundle:Inscripcion:delete" }
    requirements: { _method: post|delete }
